In [3]:
import numpy as np, pandas as pd, matplotlib.pyplot as plot

In [6]:
df = pd.read_csv("nssac-dashboard-us-county-data.csv")

In [7]:
df.head()

,FIPS,County,Province_State,Country_Region,Last_Updated,Latitude,Longitude,Confirmed,Deaths,Recovered,Active
0,1001.0,Autauga,Alabama,USA,2020-05-08 00:00:00,32.534920,-86.642749,61,3,0,58
1,1003.0,Baldwin,Alabama,USA,2020-05-08 00:00:00,30.660970,-87.749840,205,5,0,200
2,1005.0,Barbour,Alabama,USA,2020-05-08 00:00:00,31.869603,-85.393197,51,1,0,50
3,1007.0,Bibb,Alabama,USA,2020-05-08 00:00:00,32.998644,-87.126439,44,0,0,44
4,1009.0,Blount,Alabama,USA,2020-05-08 00:00:00,33.980867,-86.567371,44,0,0,44

In [15]:
print(df.describe())
print(df.describe(include=["object"]))

               FIPS     Latitude    Longitude      Confirmed        Deaths  \
count   2855.000000  2855.000000  2855.000000    2957.000000   2957.000000
mean   30231.378634    38.146455   -91.088728     436.612783     26.098072
std    15310.170218     5.126024    12.993259    3908.833597    373.305428
min     1001.000000    13.442760  -164.736740       1.000000      0.000000
25%    18122.000000    34.517190   -96.874306       7.000000      0.000000
50%    29087.000000    38.080553   -89.277254      28.000000      1.000000
75%    45044.000000    41.572654   -82.973210     126.000000      4.000000
max    78030.000000    65.508652   144.769452  183710.000000  19474.000000

          Recovered         Active
count   2957.000000    2957.000000
mean      51.852553     358.662158
std      560.343709    3535.748488
min        0.000000  -20326.000000
25%        0.000000       5.000000
50%        0.000000      21.000000
75%        1.000000     103.000000
max    20316.000000  164236.000000
         County  Province_State  Country_Region         Last_Updated
count      2957            2957            2957                 2957
unique     1734              62               1                    1
top     unknown           Texas             USA  2020-05-08 00:00:00
freq         50             219            2957                 2957

In [16]:
df.tail()

,FIPS,County,Province_State,Country_Region,Last_Updated,Latitude,Longitude,Confirmed,Deaths,Recovered,Active
2952,56037.0,Sweetwater,Wyoming,USA,2020-05-08 00:00:00,41.659496,-108.879431,19,0,0,19
2953,56039.0,Teton,Wyoming,USA,2020-05-08 00:00:00,43.934637,-110.589810,98,0,0,98
2954,56041.0,Uinta,Wyoming,USA,2020-05-08 00:00:00,41.287492,-110.547562,8,0,0,8
2955,NaN,unassigned,Wyoming,USA,2020-05-08 00:00:00,NaN,NaN,1,6,416,-421
2956,56043.0,Washakie,Wyoming,USA,2020-05-08 00:00:00,43.904997,-107.682861,8,0,0,8